/** Shared brand & industry terms included on every page */
const BASE_KEYWORDS = [
  "Xylance Technologies",
  "Xylance tech",
  "software development company",
  "IT solutions company",
  "digital agency",
  "technology partner",
  "custom software development",
  "enterprise software solutions",
  "startup technology partner",
  "SME digital transformation",
  "remote development team",
  "offshore development India",
  "India software company",
  "Chennai IT company",
  "Tamil Nadu web development",
  "affordable web development",
  "professional IT services",
  "business technology consulting",
  "scalable web applications",
  "modern web stack",
  "cloud native development",
  "agile software delivery",
  "full stack development company",
  "frontend development services",
  "backend development services",
  "API development company",
  "SaaS development company",
  "ecommerce development",
  "landing page development",
  "corporate website development",
  "responsive website design",
  "performance optimization",
  "website maintenance services",
  "UI UX design agency",
  "product design studio",
  "digital product development",
  "technology outsourcing",
  "hire dedicated developers",
  "project based development",
  "fixed price software projects",
  "time and materials development",
  "free consultation IT",
  "technology roadmap planning",
  "digital strategy consulting",
  "web app development India",
  "mobile app company India",
  "SEO agency India",
  "digital marketing agency India",
] as const;

const HOME_PAGE = [
  "web development company",
  "mobile app development company",
  "digital marketing services",
  "SEO company",
  "web design and development",
  "React development company",
  "Next.js development services",
  "TypeScript development agency",
  "Node.js development company",
  "progressive web app development",
  "single page application development",
  "headless CMS development",
  "WordPress alternative development",
  "business website builder agency",
  "small business web development",
  "enterprise web development",
  "B2B website development",
  "B2C ecommerce solutions",
  "conversion focused web design",
  "high performance websites",
  "Core Web Vitals optimization",
  "mobile first web design",
  "cross browser compatible websites",
  "accessible web development WCAG",
  "secure web application development",
  "SSL HTTPS website setup",
  "website redesign services",
  "legacy website modernization",
  "MVP development for startups",
  "prototype to production development",
  "iOS app development services",
  "Android app development services",
  "React Native app development",
  "Flutter app development company",
  "native mobile app agency",
  "app store optimization ASO",
  "mobile UI UX design",
  "Google Ads management",
  "Meta Facebook ads agency",
  "LinkedIn marketing B2B",
  "social media marketing services",
  "content marketing agency",
  "email marketing automation",
  "marketing funnel development",
  "CRO conversion rate optimization",
  "Google Analytics 4 setup",
  "technical SEO audit",
  "on page SEO services",
  "local SEO for business",
  "international SEO strategy",
  "keyword research services",
  "link building agency",
  "SEO content writing",
  "schema markup SEO",
  "search engine ranking improvement",
  "organic traffic growth",
  "lead generation website",
  "booking system development",
  "payment gateway integration",
  "CRM integration services",
  "Zapier automation agency",
  "workflow automation services",
  "business process automation",
  "real estate website development",
  "hotel website development",
  "construction company website",
  "healthcare website development",
  "education portal development",
  "restaurant ordering website",
  "portfolio website for business",
  "multilingual website development",
  "website speed optimization",
  "24/7 website support",
  "NDA protected development",
  "transparent project communication",
  "weekly sprint demos",
  "post launch support plans",
  "technology stack consulting",
  "React TypeScript experts",
  "full service digital agency",
  "trusted web development partner",
  "award winning digital solutions",
  "client focused technology firm",
  "results driven digital marketing",
  "measurable ROI campaigns",
  "brand visibility online",
  "digital presence building",
  "online business growth partner",
] as const;

const ABOUT_PAGE = [
  "about Xylance Technologies",
  "IT company profile",
  "software company mission",
  "technology company vision",
  "digital agency team",
  "experienced developers India",
  "senior engineering team",
  "design and growth specialists",
  "company values technology",
  "customer obsessed agency",
  "transparent development process",
  "craft quality software",
  "ownership driven culture",
  "trusted technology partner",
  "years of industry experience",
  "global client delivery",
  "remote first IT company",
  "cross timezone collaboration",
  "English speaking developers",
  "dedicated project managers",
  "QA testing excellence",
  "security first development",
  "accessibility focused team",
  "performance engineering culture",
  "continuous learning organization",
  "innovation driven company",
  "startup friendly agency",
  "enterprise ready delivery",
  "long term client relationships",
  "repeat business technology partner",
  "who we are IT company",
  "our story digital agency",
  "leadership technology firm",
  "company expertise overview",
  "web mobile SEO capabilities",
  "full stack competency",
  "design development marketing under one roof",
  "boutique agency personal attention",
  "scalable team augmentation",
  "white label development partner",
  "technology ethics and integrity",
  "on time project delivery",
  "budget conscious solutions",
  "scope clear proposals",
  "discovery workshop services",
  "requirements gathering experts",
  "technical documentation standards",
  "code review practices",
  "CI CD deployment maturity",
  "DevOps culture company",
  "cloud infrastructure expertise",
  "AWS Azure GCP familiarity",
  "data privacy compliance awareness",
  "GDPR friendly development",
  "secure coding standards",
  "penetration testing coordination",
  "uptime monitoring practices",
  "incident response procedures",
  "client success stories",
  "industry agnostic solutions",
  "B2B SaaS experience",
  "marketplace platform experience",
  "hospitality tech experience",
  "real estate tech experience",
  "construction industry websites",
  "local business digital help",
  "international project delivery",
  "multicultural team collaboration",
  "career technology company",
  "join our digital team",
  "partner with Xylance",
  "why choose our agency",
  "competitive technology pricing",
  "quality over quantity development",
  "human centered design approach",
  "user research driven products",
  "data informed decisions",
  "growth mindset organization",
  "sustainable software practices",
  "maintainable codebase focus",
  "documentation for handoff",
  "knowledge transfer sessions",
  "training client teams",
  "technology advisory board style",
  "roadmap prioritization help",
  "MVP to scale journey partner",
  "product market fit support",
  "go to market digital support",
  "brand and technology alignment",
  "corporate profile IT services",
  "about our development process",
  "about our design process",
  "about our marketing services",
  "company FAQ technology",
  "credentials software firm",
  "certified developers team",
  "professional IT consultants",
] as const;

const SERVICES_PAGE = [
  "web development services",
  "custom web application development",
  "React web development",
  "Next.js website development",
  "TypeScript web applications",
  "Node.js backend development",
  "REST API development",
  "GraphQL API services",
  "PostgreSQL database development",
  "MongoDB application development",
  "headless Shopify development",
  "WooCommerce custom development",
  "membership site development",
  "subscription billing integration",
  "mobile app development services",
  "iOS Swift app development",
  "Android Kotlin development",
  "React Native cross platform apps",
  "mobile backend Firebase",
  "push notification implementation",
  "offline first mobile apps",
  "App Store submission help",
  "Play Store launch support",
  "mobile app maintenance",
  "UI UX design services",
  "Figma design to code",
  "design system creation",
  "wireframing prototyping",
  "user journey mapping",
  "usability testing services",
  "interaction design agency",
  "digital marketing services",
  "performance marketing agency",
  "Google search ads management",
  "display advertising campaigns",
  "retargeting ad strategy",
  "social media ad creatives",
  "TikTok ads for brands",
  "influencer campaign support",
  "marketing automation setup",
  "HubSpot integration services",
  "Klaviyo email flows",
  "SEO optimization services",
  "technical SEO fixes",
  "site architecture SEO",
  "Core Web Vitals SEO",
  "content strategy SEO",
  "blog SEO writing",
  "local Google Business Profile SEO",
  "multi location SEO",
  "ecommerce SEO optimization",
  "international hreflang SEO",
  "competitor SEO analysis",
  "SEO monthly reporting",
  "automation services business",
  "Zapier Make n8n integration",
  "CRM marketing sync",
  "lead routing automation",
  "invoice workflow automation",
  "Slack notification integrations",
  "custom webhook development",
  "RPA style automation",
  "reporting dashboard automation",
  "API integration specialists",
  "third party SaaS integration",
  "payment Stripe Razorpay integration",
  "shipping logistics API integration",
  "inventory sync development",
  "booking calendar integration",
  "live chat integration",
  "analytics tag management",
  "server side tracking setup",
  "A/B testing implementation",
  "heatmap session recording setup",
  "website hosting guidance",
  "CDN configuration help",
  "domain DNS setup support",
  "SSL certificate management",
  "website backup solutions",
  "disaster recovery planning",
  "managed website updates",
  "security patch management",
  "malware removal support",
  "DDoS protection guidance",
  "WCAG accessibility remediation",
  "multilingual i18n development",
  "RTL language website support",
  "PWA installable web apps",
  "SSR SSG architecture consulting",
  "microservices architecture help",
  "monolith to modular refactor",
  "legacy PHP migration React",
  "WordPress headless decoupled",
  "service level agreement IT",
  "monthly retainer development",
  "dedicated developer hiring",
  "sprint based delivery model",
] as const;

const PROJECTS_PAGE = [
  "web development portfolio",
  "mobile app portfolio",
  "case studies digital agency",
  "client projects showcase",
  "recent website launches",
  "featured work technology",
  "Dazzle Drop Inn hotel website",
  "hospitality website portfolio",
  "hotel booking website design",
  "luxury hotel web development",
  "PM Constructions website",
  "construction company portfolio",
  "real estate website projects",
  "Chennai Builders website",
  "property listing website",
  "lead capture real estate site",
  "commercial construction web design",
  "residential builder website",
  "architecture firm portfolio site",
  "before after website redesign",
  "responsive portfolio examples",
  "high converting landing pages",
  "ecommerce project samples",
  "SaaS dashboard UI projects",
  "startup MVP case study",
  "enterprise portal development sample",
  "nonprofit website example",
  "education LMS project",
  "healthcare patient portal sample",
  "fitness app portfolio piece",
  "food delivery app UI",
  "marketplace platform case study",
  "booking engine implementation",
  "payment flow UX case study",
  "multi vendor ecommerce sample",
  "B2B lead gen website results",
  "SEO ranking improvement case",
  "traffic growth case study",
  "conversion uplift project",
  "page speed optimization result",
  "mobile traffic increase project",
  "Google PageSpeed 90+ project",
  "accessibility audit fix project",
  "CMS migration case study",
  "React migration legacy site",
  "design system rollout project",
  "brand refresh website project",
  "international website localization",
  "multisite WordPress alternative",
  "headless content project",
  "API first integration project",
  "automation workflow case study",
  "marketing funnel build sample",
  "Google Ads ROAS case study",
  "social ads lead gen case",
  "email list growth project",
  "content hub SEO project",
  "local SEO ranking case Chennai",
  "review generation website feature",
  "chatbot integration project",
  "WhatsApp business integration site",
  "CRM HubSpot website sync case",
  "inventory management portal",
  "employee intranet development",
  "customer self service portal",
  "subscription SaaS billing UI",
  "analytics dashboard development",
  "data visualization web app",
  "map based property search UI",
  "virtual tour website feature",
  "video background hero website",
  "animation rich marketing site",
  "minimal corporate website design",
  "bold creative agency portfolio",
  "dark mode website implementation",
  "glassmorphism UI website",
  "gold luxury brand website",
  "trust badges testimonial layout",
  "client logo marquee website",
  "case study detail page SEO",
  "portfolio filter by industry",
  "project gallery masonry layout",
  "lazy load image optimization project",
  "CDN image delivery project",
  "Lighthouse performance case",
  "Core Web Vitals pass project",
  "structured data rich results project",
  "schema for local business site",
  "FAQ schema implementation project",
  "open graph social preview project",
  "vercel deployment case study",
  "cloudflare pages migration",
  "aws amplify hosting project",
  "dockerized Node deployment",
  "CI pipeline GitHub Actions project",
  "test coverage improvement project",
  "playwright E2E testing setup",
  "design handoff Figma to React",
  "component library Storybook project",
  "Tailwind CSS redesign project",
  "framer motion animation website",
  "accessible form design project",
  "GDPR cookie consent implementation",
  "privacy policy terms generator integration",
  "multistep quote request form project",
  "live project maintenance retainer",
] as const;

const CONTACT_PAGE = [
  "contact Xylance Technologies",
  "hire web developers",
  "request project quote",
  "free consultation web development",
  "contact digital agency",
  "get in touch IT company",
  "email software company",
  "call web development team",
  "WhatsApp business inquiry",
  "remote project inquiry form",
  "send project requirements",
  "book discovery call",
  "schedule technical consultation",
  "RFP software development",
  "proposal request website",
  "mobile app quote request",
  "SEO audit request form",
  "marketing strategy inquiry",
  "UI UX design consultation",
  "automation project inquiry",
  "support ticket website help",
  "existing client contact",
  "partnership inquiry technology",
  "vendor collaboration contact",
  "career inquiry technology jobs",
  "internship application contact",
  "media press contact technology",
  "sales contact software agency",
  "customer service IT company",
  "technical support contact",
  "billing accounts contact",
  "office remote contact details",
  "India phone web development",
  "Chennai contact IT services",
  "Tamil Nadu software inquiry",
  "international client contact",
  "timezone flexible meetings",
  "video call project discussion",
  "NDA before project discussion",
  "confidential project inquiry",
  "startup founder contact",
  "enterprise procurement contact",
  "agency white label contact",
  "referral partner contact",
  "affiliate program inquiry",
  "urgent website fix contact",
  "hackathon sponsor contact",
  "nonprofit discount inquiry",
  "education institution contact",
  "government tender inquiry IT",
  "maintenance contract inquiry",
  "hosting migration help contact",
  "domain email setup help",
  "Google Business verification help",
  "analytics setup assistance contact",
  "accessibility compliance inquiry",
  "security incident report contact",
  "data breach support contact",
  "privacy GDPR question contact",
  "cookie policy question contact",
  "terms of service question",
  "refund policy inquiry services",
  "project timeline question contact",
  "pricing estimate request",
  "hourly rate inquiry developers",
  "dedicated team cost inquiry",
  "fixed price project contact",
  "milestone payment discussion",
  "invoice payment question",
  "contract signing contact",
  "legal entity verification contact",
  "GST invoice India contact",
  "export services inquiry India",
  "offshore team contact India",
  "nearshore alternative contact",
  "English project communication",
  "Hindi Tamil support optional",
  "documentation request contact",
  "portfolio walkthrough request",
  "reference check client list",
  "testimonial request contact",
  "case study deep dive meeting",
  "competitor comparison discussion",
  "technology stack recommendation request",
  "architecture review session booking",
  "code audit request contact",
  "performance audit booking",
  "SEO site review booking",
  "marketing audit booking",
  "UX critique session contact",
  "workshop facilitation inquiry",
  "training session booking contact",
  "retainer plan discussion contact",
  "SLA support plan inquiry",
  "emergency hotline web down",
  "404 fix urgent contact",
  "SSL certificate renewal help",
  "email deliverability setup contact",
  "spam form protection inquiry",
  "CAPTCHA integration request",
  "newsletter integration contact",
  "Web3Forms contact setup help",
  "chatbot integration contact",
  "live chat setup contact",
  "CRM lead form integration",
  "calendar booking Calendly setup",
  "thank you page optimization contact",
] as const;

function mergeKeywords(...groups: readonly string[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const group of groups) {
    for (const keyword of group) {
      const normalized = keyword.trim();
      if (!normalized || seen.has(normalized)) continue;
      seen.add(normalized);
      result.push(normalized);
    }
  }
  return result;
}

/** Returns up to `limit` unique keywords (default 100) for a page */
export function getPageKeywords(
  page: "home" | "about" | "services" | "projects" | "contact",
  limit = 100,
): string[] {
  const pools: Record<typeof page, readonly string[][]> = {
    home: [BASE_KEYWORDS, HOME_PAGE],
    about: [BASE_KEYWORDS, ABOUT_PAGE],
    services: [BASE_KEYWORDS, SERVICES_PAGE, HOME_PAGE.slice(0, 20)],
    projects: [BASE_KEYWORDS, PROJECTS_PAGE, HOME_PAGE.slice(0, 15)],
    contact: [BASE_KEYWORDS, CONTACT_PAGE, HOME_PAGE.slice(0, 10)],
  };

  return mergeKeywords(...pools[page]).slice(0, limit);
}

export const KEYWORD_COUNT = 100;
